---
- hosts: appVMs
  vars:
    client: "{{client_id}}"
    ten: "{{tenant_id}}"
    secret: "{{sec}}"
    sub_id: "{{subs_id}}"
  become: yes
  
  tasks:
    - name: Download artifact
      azure.azcollection.azure_rm_storageblob:
       resource_group: Week6-Project
       storage_account_name: idanmlstorage
       container: jenkins
       blob: artifact.tar.gz
       dest: ~/app/artifact.tar.gz
       client_id: "{{client}}"
       tenant: "{{ten}}"
       secret: "{{secret}}"
       subscription_id: "{{sub_id}}"