---
- hosts: APPVMs
  vars:
    client: "{{client_id}}"
    ten: "{{tenane_id}}"
    secret: "{{sec}}"
  become: yes
  tasks:

    - name: Download artifact
      azure_rm_storageblob:
      resource_group: Week6-Project
      storage_account_name: idanmlstorage
      container: idanmlstorage
      blob: artifact.tar.gz
      dest: ~/app/artifact.tar.gz
      client_id: "{{client}}"
      tenant: "{{ten}}"
      secret: "{{secret}}"